name = "StanLogDensityProblems"
uuid = "a545de4d-8dba-46db-9d34-4e41d3f07807"
authors = ["Seth Axen <seth@sethaxen.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
