name = "StanLogDensityProblems"
uuid = "a545de4d-8dba-46db-9d34-4e41d3f07807"
authors = ["Seth Axen <seth@sethaxen.com> and contributors"]
version = "0.1.0"

[deps]
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"

[compat]
BridgeStan = "1.0.1"
LogDensityProblems = "1, 2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
